name = "qest-bootstrap"
main = "src/index.js"
compatibility_date = "2026-04-08"
workers_dev = true
preview_urls = true
routes = [
  { pattern = "install.brainafk.in/*", zone_name = "brainafk.in" }
]

[observability]
enabled = true
